FROM adoptopenjdk/openjdk17

# Copy the jar file to the container
COPY target/chatgpt-microservice-0.0.1-SNAPSHOT.jar /app/chatgpt-microservice.jar

# Set the working directory to /app
WORKDIR /app

# Expose port 8080 for the container
EXPOSE 8080

# Run the microservice
CMD ["java", "-jar", "chatgpt-microservice.jar"]
